### ISSUE TITLE
HTTP Status 404 - /JavaBridge/ The requested resource is not available

### ISSUE THREAD

**Issue by hemaliv** [aspose-email/Aspose.Email-for-Java#27]
![screenshot 3](https://user-images.githubusercontent.com/30138930/28524787-8bee2ea4-709f-11e7-8ed1-28b3b271e69f.png)

**Comment by kashifiqb** [comment]
@hemaliv ,
Could you please share more details with us about the code sample you are trying at your end? We are not sure if you are running one of the examples from here or is it some other code? Your feedback will help us investigate the issue further.
