### ISSUE TITLE
personal storage class not found

### ISSUE THREAD

**Issue by Saeedullah12355** [aspose-email/Aspose.Email-for-Java#30]

**Comment by kashifiqb** [comment]
@Saeedullah12355 ,

Could you please share more details about the error you are facing? You need to use following import statement in your application to use PersonalStorage class.

import com.aspose.email.PersonalStorage;

Please let us know if you still face some issue. You can also get technical support by reaching us over [Aspose.Email forum](https://forums.aspose.com/c/email).
