### ISSUE TITLE
Aspose.Email for Java is used to convert msg of outlook to html or text is free?

### ISSUE THREAD

**Issue by whaozl** [aspose-email/Aspose.Email-for-Java#40]

**Comment by andreypotapovaspose** [comment]
@whaozl,
We apologize for the long answer. Thank you for your interest in Aspose.Email.

You can use Aspose.Email for Java free with some [limitations](https://docs.aspose.com/email/java/licensing/#evaluation-version-limitations).

If you have any questions or issues found, please post them on [Aspose.Email forum](https://forum.aspose.com/c/email/).
